<?php

use Illuminate\Support\Facades\DB;
use Tests\TestCase;

uses(TestCase::class);

test('sequence repair is skipped on other database drivers', function () {
    DB::shouldReceive('getDriverName')->once()->andReturn('sqlite');
    DB::shouldReceive('statement')->never();

    $migration = require database_path('migrations/2026_10_02_223239_repair_guest_group_user_postgres_sequence.php');
    $migration->up();
});

test('postgres sequence repair preserves rows and generates a safe next id', function (string $definition, ?int $existingId, int $sequenceValue, bool $isCalled, int $expectedId) {
    if (DB::getDriverName() !== 'pgsql') {
        $this->markTestSkipped('Run with a PostgreSQL connection; this test only creates a temporary table.');
    }

    DB::beginTransaction();

    try {
        DB::statement("CREATE TEMPORARY TABLE guest_group_user (id {$definition} PRIMARY KEY) ON COMMIT DROP");

        if ($existingId !== null) {
            DB::table('guest_group_user')->insert(['id' => $existingId]);
        }

        $sequence = DB::selectOne("SELECT pg_get_serial_sequence('guest_group_user', 'id') AS name")->name;
        DB::select('SELECT setval(?::regclass, ?, ?::boolean)', [$sequence, $sequenceValue, $isCalled ? 'true' : 'false']);

        if ($definition === 'bigserial') {
            DB::statement("ALTER SEQUENCE {$sequence} OWNED BY NONE");
        }

        $migration = require database_path('migrations/2026_10_02_223239_repair_guest_group_user_postgres_sequence.php');
        $migration->up();
        $migration->up();

        expect(DB::table('guest_group_user')->insertGetId([]))->toBe($expectedId);

        if ($existingId !== null) {
            expect(DB::table('guest_group_user')->where('id', $existingId)->exists())->toBeTrue();
        }
    } finally {
        DB::rollBack();
    }
})->with([
    'imported serial without ownership' => ['bigserial', 85, 2, true, 86],
    'identity column' => ['bigint GENERATED BY DEFAULT AS IDENTITY', 85, 2, true, 86],
    'already ahead' => ['bigserial', 85, 100, true, 101],
    'unused conflicting value' => ['bigserial', 2, 2, false, 3],
    'empty table' => ['bigserial', null, 1, false, 1],
]);
